"""add_uploads_playlist_id_and_rapid_tracking

Revision ID: 1f28cfc96f28
Revises: fdba3a221e8d
Create Date: 2026-03-20 14:37:54.762296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f28cfc96f28'
down_revision: Union[str, Sequence[str], None] = 'fdba3a221e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('uploads_playlist_id', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('rapid_tracking_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'rapid_tracking_until')
    op.drop_column('channels', 'uploads_playlist_id')
    # ### end Alembic commands ###
