"""add anomaly_events table and fetchlog channel_id

Revision ID: 793794bae226
Revises: 1f28cfc96f28
Create Date: 2026-03-21 12:10:54.524267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "793794bae226"
down_revision: Union[str, Sequence[str], None] = "1f28cfc96f28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomaly_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("metric_name", sa.String(length=50), nullable=True),
        sa.Column("metric_value", sa.Float(), nullable=True),
        sa.Column("baseline_value", sa.Float(), nullable=True),
        sa.Column("deviation_score", sa.Float(), nullable=True),
        sa.Column("is_acknowledged", sa.Boolean(), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_anomaly_events_channel_id"),
        "anomaly_events",
        ["channel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anomaly_events_video_id"), "anomaly_events", ["video_id"], unique=False
    )
    op.add_column("fetch_logs", sa.Column("channel_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_fetch_logs_channel_id"), "fetch_logs", ["channel_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fetch_logs_channel_id"), table_name="fetch_logs")
    op.drop_column("fetch_logs", "channel_id")
    op.drop_index(op.f("ix_anomaly_events_video_id"), table_name="anomaly_events")
    op.drop_index(op.f("ix_anomaly_events_channel_id"), table_name="anomaly_events")
    op.drop_table("anomaly_events")
    # ### end Alembic commands ###
